# Generated by Django 4.1.2 on 2022-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone_book',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
