# Generated by Django 4.1.2 on 2022-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb_app', '0002_rename_id_phone_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_book',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone_book',
            name='Phone_Number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
